apiVersion: apps/v1
kind: Deployment
metadata:
  name: theidserver-private
spec:
  selector:
    matchLabels:
      app: theidserver-private
  replicas: 2
  template:
    metadata:
      labels:
        app: theidserver-private
        role: backend
    spec:
      containers:
      - image: aguacongas/aguacongastheidserver:preview-1.0.0
        name: theidserver-private
        ports:
        - containerPort: 443
        envFrom: 
        - configMapRef:
            name: private-config
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: theideserver-connectionstring
              key: ConnectionString
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: theidserver-tls
              key: tls.pwd
        - name: IdentityServer__Key__Password
          valueFrom:
            secretKeyRef:
              name: theidserver-tls
              key: sign-key
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/share/ca-certificates
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: config
