apiVersion: v1
kind: ConfigMap
metadata:
  name: private-config
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_Kestrel__Certificates__Default__Path: /usr/local/share/ca-certificates/tls.pfx
  ASPNETCORE_URLS: https://+
  DisableStrictSsl: "true"
  EnableOpenApiDoc: "false"
  IdentityServer__Key__Type: File
  IdentityServer__Key__FilePath: /usr/local/share/ca-certificates/theidserver.pfx
  ApiAuthentication__Authority: https://localhost
  ApiAuthentication__IntrospectionDiscoveryPolicy__ValidateIssuerName: "false"
  EmailApiAuthentication__Authority: https://localhost
  EmailApiAuthentication__ApiUrl: https://localhost/api/email
  SignalR__HubOptions__EnableDetailedErrors: "true"
  SignalR__UseMessagePack: "true"
  SignalR__RedisConnectionString: "redis:6379"
  SignalR__RedisOptions__Configuration__ChannelPrefix: TheIdServer
  Serilog__WriteTo__0__Args__serverUrl: http://seq:5341
  Serilog__WriteTo__0__Args__apiKey: T9OBdJpuMS4nsRgTRzaP
